
services:
  db:
    image: postgres:16-alpine # Ou a versão que preferir, alpine é mais leve
    container_name: meu_postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_hotel # Nome do seu banco de dados
      POSTGRES_USER: root # Nome do usuário do banco de dados
      POSTGRES_PASSWORD: root # Senha do usuário do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste os dados do banco
    ports:
      - "5432:5432" # Mapeia a porta do container para a porta da sua máquina

  pgadmin:
    image: dpage/pgadmin4 # Imagem oficial do pgAdmin
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@email.com # Email de login do pgAdmin
      PGADMIN_DEFAULT_PASSWORD: root # Senha de login do pgAdmin
      PGADMIN_LISTEN_PORT: 80 # Porta interna que o pgAdmin escuta
    ports:
      - "8081:80" # Mapeia a porta 80 do container para a porta 8080 da sua máquina
    volumes:
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json  
      - ./scripts:/var/lib/pgadmin/sql_scripts 
    depends_on:
      - db # Garante que o pgAdmin só inicie depois do banco de dados

volumes:
  postgres_data: # Define o volume para persistência dos dados do PostgreSQL
